/**************************************************************************//**
 * @file
 * @brief
 * @version  V1.00
 * @date     28. Sep 2012
 *
 * @note
 * Copyright (C) REnergy Micro-Electronics Co.,LTD.
 *
 *
 ******************************************************************************/

/** @addtogroup RN8213_Definitions RN8213 Definitions
  This file defines all structures and symbols for RN8213:
    - registers and bitfields
    - peripheral base address
    - peripheral ID
    - Peripheral definitions
  @{
*/

#include <CoreSupport.h>

//寄存器地址为addr的第bitnum位的bitband地址获取
#define BIT_ADDR(addr,bitnum) ((addr&0xFC000000) + 0x02000000 + (bitnum<<2) + ((addr<<5)&0x03FFFFFF))

//寄存器地址为addr的第bitnum位的指针
#define BIT_POINT(addr,bitnum) *((__IO uint32_t *)(BIT_ADDR(addr,bitnum)))

//--------------PMA----------------
#define PMA_P00 BIT_POINT((uint32_t)(&(GPIO->PMA)),0)
#define PMA_P01 BIT_POINT((uint32_t)(&(GPIO->PMA)),1)
#define PMA_P02 BIT_POINT((uint32_t)(&(GPIO->PMA)),2)
#define PMA_P03 BIT_POINT((uint32_t)(&(GPIO->PMA)),3)
#define PMA_P04 BIT_POINT((uint32_t)(&(GPIO->PMA)),4)

#define PMA_P10 BIT_POINT((uint32_t)(&(GPIO->PMA)),8)
#define PMA_P11 BIT_POINT((uint32_t)(&(GPIO->PMA)),9)
#define PMA_P12 BIT_POINT((uint32_t)(&(GPIO->PMA)),10)
#define PMA_P13 BIT_POINT((uint32_t)(&(GPIO->PMA)),11)
#define PMA_P14 BIT_POINT((uint32_t)(&(GPIO->PMA)),12)
#define PMA_P15 BIT_POINT((uint32_t)(&(GPIO->PMA)),13)
#define PMA_P16 BIT_POINT((uint32_t)(&(GPIO->PMA)),14)
#define PMA_P17 BIT_POINT((uint32_t)(&(GPIO->PMA)),15)

#define PMA_P20 BIT_POINT((uint32_t)(&(GPIO->PMA)),16)
#define PMA_P21 BIT_POINT((uint32_t)(&(GPIO->PMA)),17)
#define PMA_P22 BIT_POINT((uint32_t)(&(GPIO->PMA)),18)
#define PMA_P23 BIT_POINT((uint32_t)(&(GPIO->PMA)),19)
#define PMA_P24 BIT_POINT((uint32_t)(&(GPIO->PMA)),20)
#define PMA_P25 BIT_POINT((uint32_t)(&(GPIO->PMA)),21)
#define PMA_P26 BIT_POINT((uint32_t)(&(GPIO->PMA)),22)
#define PMA_P27 BIT_POINT((uint32_t)(&(GPIO->PMA)),23)

#define PMA_P30 BIT_POINT((uint32_t)(&(GPIO->PMA)),24)
#define PMA_P31 BIT_POINT((uint32_t)(&(GPIO->PMA)),25)
#define PMA_P32 BIT_POINT((uint32_t)(&(GPIO->PMA)),26)
#define PMA_P33 BIT_POINT((uint32_t)(&(GPIO->PMA)),27)
#define PMA_P34 BIT_POINT((uint32_t)(&(GPIO->PMA)),28)
#define PMA_P35 BIT_POINT((uint32_t)(&(GPIO->PMA)),29)
#define PMA_P36 BIT_POINT((uint32_t)(&(GPIO->PMA)),30)
#define PMA_P37 BIT_POINT((uint32_t)(&(GPIO->PMA)),31)

//----------------------PA---------------------------
#define PA_P00 BIT_POINT((uint32_t)(&(GPIO->PA)),0)
#define PA_P01 BIT_POINT((uint32_t)(&(GPIO->PA)),1)
#define PA_P02 BIT_POINT((uint32_t)(&(GPIO->PA)),2)
#define PA_P03 BIT_POINT((uint32_t)(&(GPIO->PA)),3)
#define PA_P04 BIT_POINT((uint32_t)(&(GPIO->PA)),4)

#define PA_P10 BIT_POINT((uint32_t)(&(GPIO->PA)),8)
#define PA_P11 BIT_POINT((uint32_t)(&(GPIO->PA)),9)
#define PA_P12 BIT_POINT((uint32_t)(&(GPIO->PA)),10)
#define PA_P13 BIT_POINT((uint32_t)(&(GPIO->PA)),11)
#define PA_P14 BIT_POINT((uint32_t)(&(GPIO->PA)),12)
#define PA_P15 BIT_POINT((uint32_t)(&(GPIO->PA)),13)
#define PA_P16 BIT_POINT((uint32_t)(&(GPIO->PA)),14)
#define PA_P17 BIT_POINT((uint32_t)(&(GPIO->PA)),15)

#define PA_P20 BIT_POINT((uint32_t)(&(GPIO->PA)),16)
#define PA_P21 BIT_POINT((uint32_t)(&(GPIO->PA)),17)
#define PA_P22 BIT_POINT((uint32_t)(&(GPIO->PA)),18)
#define PA_P23 BIT_POINT((uint32_t)(&(GPIO->PA)),19)
#define PA_P24 BIT_POINT((uint32_t)(&(GPIO->PA)),20)
#define PA_P25 BIT_POINT((uint32_t)(&(GPIO->PA)),21)
#define PA_P26 BIT_POINT((uint32_t)(&(GPIO->PA)),22)
#define PA_P27 BIT_POINT((uint32_t)(&(GPIO->PA)),23)

#define PA_P30 BIT_POINT((uint32_t)(&(GPIO->PA)),24)
#define PA_P31 BIT_POINT((uint32_t)(&(GPIO->PA)),25)
#define PA_P32 BIT_POINT((uint32_t)(&(GPIO->PA)),26)
#define PA_P33 BIT_POINT((uint32_t)(&(GPIO->PA)),27)
#define PA_P34 BIT_POINT((uint32_t)(&(GPIO->PA)),28)
#define PA_P35 BIT_POINT((uint32_t)(&(GPIO->PA)),29)
#define PA_P36 BIT_POINT((uint32_t)(&(GPIO->PA)),30)
#define PA_P37 BIT_POINT((uint32_t)(&(GPIO->PA)),31)

//----------------------PCA0---------------------------
#define PCA0_P00 BIT_POINT((uint32_t)(&(GPIO->PCA0)),0)
#define PCA0_P01 BIT_POINT((uint32_t)(&(GPIO->PCA0)),1)
#define PCA0_P02 BIT_POINT((uint32_t)(&(GPIO->PCA0)),2)
#define PCA0_P03 BIT_POINT((uint32_t)(&(GPIO->PCA0)),3)
#define PCA0_P04 BIT_POINT((uint32_t)(&(GPIO->PCA0)),4)

#define PCA0_P10 BIT_POINT((uint32_t)(&(GPIO->PCA0)),8)
#define PCA0_P11 BIT_POINT((uint32_t)(&(GPIO->PCA0)),9)
#define PCA0_P12 BIT_POINT((uint32_t)(&(GPIO->PCA0)),10)
#define PCA0_P13 BIT_POINT((uint32_t)(&(GPIO->PCA0)),11)
#define PCA0_P14 BIT_POINT((uint32_t)(&(GPIO->PCA0)),12)
#define PCA0_P15 BIT_POINT((uint32_t)(&(GPIO->PCA0)),13)
#define PCA0_P16 BIT_POINT((uint32_t)(&(GPIO->PCA0)),14)
#define PCA0_P17 BIT_POINT((uint32_t)(&(GPIO->PCA0)),15)

#define PCA0_P20 BIT_POINT((uint32_t)(&(GPIO->PCA0)),16)
#define PCA0_P21 BIT_POINT((uint32_t)(&(GPIO->PCA0)),17)
#define PCA0_P22 BIT_POINT((uint32_t)(&(GPIO->PCA0)),18)
#define PCA0_P23 BIT_POINT((uint32_t)(&(GPIO->PCA0)),19)
#define PCA0_P24 BIT_POINT((uint32_t)(&(GPIO->PCA0)),20)
#define PCA0_P25 BIT_POINT((uint32_t)(&(GPIO->PCA0)),21)
#define PCA0_P26 BIT_POINT((uint32_t)(&(GPIO->PCA0)),22)
#define PCA0_P27 BIT_POINT((uint32_t)(&(GPIO->PCA0)),23)

#define PCA0_P30 BIT_POINT((uint32_t)(&(GPIO->PCA0)),24)
#define PCA0_P31 BIT_POINT((uint32_t)(&(GPIO->PCA0)),25)
#define PCA0_P32 BIT_POINT((uint32_t)(&(GPIO->PCA0)),26)
#define PCA0_P33 BIT_POINT((uint32_t)(&(GPIO->PCA0)),27)
#define PCA0_P34 BIT_POINT((uint32_t)(&(GPIO->PCA0)),28)
#define PCA0_P35 BIT_POINT((uint32_t)(&(GPIO->PCA0)),29)
#define PCA0_P36 BIT_POINT((uint32_t)(&(GPIO->PCA0)),30)
#define PCA0_P37 BIT_POINT((uint32_t)(&(GPIO->PCA0)),31)

//----------------------PCA1---------------------------
#define PCA1_P00 BIT_POINT((uint32_t)(&(GPIO->PCA1)),0)
#define PCA1_P01 BIT_POINT((uint32_t)(&(GPIO->PCA1)),1)
#define PCA1_P02 BIT_POINT((uint32_t)(&(GPIO->PCA1)),2)
#define PCA1_P03 BIT_POINT((uint32_t)(&(GPIO->PCA1)),3)
#define PCA1_P04 BIT_POINT((uint32_t)(&(GPIO->PCA1)),4)

#define PCA1_P10 BIT_POINT((uint32_t)(&(GPIO->PCA1)),8)
#define PCA1_P11 BIT_POINT((uint32_t)(&(GPIO->PCA1)),9)
#define PCA1_P12 BIT_POINT((uint32_t)(&(GPIO->PCA1)),10)
#define PCA1_P13 BIT_POINT((uint32_t)(&(GPIO->PCA1)),11)
#define PCA1_P14 BIT_POINT((uint32_t)(&(GPIO->PCA1)),12)
#define PCA1_P15 BIT_POINT((uint32_t)(&(GPIO->PCA1)),13)
#define PCA1_P16 BIT_POINT((uint32_t)(&(GPIO->PCA1)),14)
#define PCA1_P17 BIT_POINT((uint32_t)(&(GPIO->PCA1)),15)

#define PCA1_P20 BIT_POINT((uint32_t)(&(GPIO->PCA1)),16)
#define PCA1_P21 BIT_POINT((uint32_t)(&(GPIO->PCA1)),17)
#define PCA1_P22 BIT_POINT((uint32_t)(&(GPIO->PCA1)),18)
#define PCA1_P23 BIT_POINT((uint32_t)(&(GPIO->PCA1)),19)
#define PCA1_P24 BIT_POINT((uint32_t)(&(GPIO->PCA1)),20)
#define PCA1_P25 BIT_POINT((uint32_t)(&(GPIO->PCA1)),21)
#define PCA1_P26 BIT_POINT((uint32_t)(&(GPIO->PCA1)),22)
#define PCA1_P27 BIT_POINT((uint32_t)(&(GPIO->PCA1)),23)

#define PCA1_P30 BIT_POINT((uint32_t)(&(GPIO->PCA1)),24)
#define PCA1_P31 BIT_POINT((uint32_t)(&(GPIO->PCA1)),25)
#define PCA1_P32 BIT_POINT((uint32_t)(&(GPIO->PCA1)),26)
#define PCA1_P33 BIT_POINT((uint32_t)(&(GPIO->PCA1)),27)
#define PCA1_P34 BIT_POINT((uint32_t)(&(GPIO->PCA1)),28)
#define PCA1_P35 BIT_POINT((uint32_t)(&(GPIO->PCA1)),29)
#define PCA1_P36 BIT_POINT((uint32_t)(&(GPIO->PCA1)),30)
#define PCA1_P37 BIT_POINT((uint32_t)(&(GPIO->PCA1)),31)

//----------------------PUA---------------------------
#define PUA_P00 BIT_POINT((uint32_t)(&(GPIO->PUA)),0)
#define PUA_P01 BIT_POINT((uint32_t)(&(GPIO->PUA)),1)
#define PUA_P02 BIT_POINT((uint32_t)(&(GPIO->PUA)),2)
#define PUA_P03 BIT_POINT((uint32_t)(&(GPIO->PUA)),3)
#define PUA_P04 BIT_POINT((uint32_t)(&(GPIO->PUA)),4)

#define PUA_P10 BIT_POINT((uint32_t)(&(GPIO->PUA)),8)
#define PUA_P11 BIT_POINT((uint32_t)(&(GPIO->PUA)),9)
#define PUA_P12 BIT_POINT((uint32_t)(&(GPIO->PUA)),10)
#define PUA_P13 BIT_POINT((uint32_t)(&(GPIO->PUA)),11)
#define PUA_P14 BIT_POINT((uint32_t)(&(GPIO->PUA)),12)
#define PUA_P15 BIT_POINT((uint32_t)(&(GPIO->PUA)),13)
#define PUA_P16 BIT_POINT((uint32_t)(&(GPIO->PUA)),14)
#define PUA_P17 BIT_POINT((uint32_t)(&(GPIO->PUA)),15)

#define PUA_P20 BIT_POINT((uint32_t)(&(GPIO->PUA)),16)
#define PUA_P21 BIT_POINT((uint32_t)(&(GPIO->PUA)),17)
#define PUA_P22 BIT_POINT((uint32_t)(&(GPIO->PUA)),18)
#define PUA_P23 BIT_POINT((uint32_t)(&(GPIO->PUA)),19)
#define PUA_P24 BIT_POINT((uint32_t)(&(GPIO->PUA)),20)
#define PUA_P25 BIT_POINT((uint32_t)(&(GPIO->PUA)),21)
#define PUA_P26 BIT_POINT((uint32_t)(&(GPIO->PUA)),22)
#define PUA_P27 BIT_POINT((uint32_t)(&(GPIO->PUA)),23)

#define PUA_P30 BIT_POINT((uint32_t)(&(GPIO->PUA)),24)
#define PUA_P31 BIT_POINT((uint32_t)(&(GPIO->PUA)),25)
#define PUA_P32 BIT_POINT((uint32_t)(&(GPIO->PUA)),26)
#define PUA_P33 BIT_POINT((uint32_t)(&(GPIO->PUA)),27)
#define PUA_P34 BIT_POINT((uint32_t)(&(GPIO->PUA)),28)
#define PUA_P35 BIT_POINT((uint32_t)(&(GPIO->PUA)),29)
#define PUA_P36 BIT_POINT((uint32_t)(&(GPIO->PUA)),30)
#define PUA_P37 BIT_POINT((uint32_t)(&(GPIO->PUA)),31)

//----------------------PIMA---------------------------
#define PIMA_P00 BIT_POINT((uint32_t)(&(GPIO->PIMA)),0)
#define PIMA_P01 BIT_POINT((uint32_t)(&(GPIO->PIMA)),1)
#define PIMA_P02 BIT_POINT((uint32_t)(&(GPIO->PIMA)),2)
#define PIMA_P03 BIT_POINT((uint32_t)(&(GPIO->PIMA)),3)
#define PIMA_P04 BIT_POINT((uint32_t)(&(GPIO->PIMA)),4)

#define PIMA_P10 BIT_POINT((uint32_t)(&(GPIO->PIMA)),8)
#define PIMA_P11 BIT_POINT((uint32_t)(&(GPIO->PIMA)),9)
#define PIMA_P12 BIT_POINT((uint32_t)(&(GPIO->PIMA)),10)
#define PIMA_P13 BIT_POINT((uint32_t)(&(GPIO->PIMA)),11)
#define PIMA_P14 BIT_POINT((uint32_t)(&(GPIO->PIMA)),12)
#define PIMA_P15 BIT_POINT((uint32_t)(&(GPIO->PIMA)),13)
#define PIMA_P16 BIT_POINT((uint32_t)(&(GPIO->PIMA)),14)
#define PIMA_P17 BIT_POINT((uint32_t)(&(GPIO->PIMA)),15)

#define PIMA_P20 BIT_POINT((uint32_t)(&(GPIO->PIMA)),16)
#define PIMA_P21 BIT_POINT((uint32_t)(&(GPIO->PIMA)),17)
#define PIMA_P22 BIT_POINT((uint32_t)(&(GPIO->PIMA)),18)
#define PIMA_P23 BIT_POINT((uint32_t)(&(GPIO->PIMA)),19)
#define PIMA_P24 BIT_POINT((uint32_t)(&(GPIO->PIMA)),20)
#define PIMA_P25 BIT_POINT((uint32_t)(&(GPIO->PIMA)),21)
#define PIMA_P26 BIT_POINT((uint32_t)(&(GPIO->PIMA)),22)
#define PIMA_P27 BIT_POINT((uint32_t)(&(GPIO->PIMA)),23)

#define PIMA_P30 BIT_POINT((uint32_t)(&(GPIO->PIMA)),24)
#define PIMA_P31 BIT_POINT((uint32_t)(&(GPIO->PIMA)),25)
#define PIMA_P32 BIT_POINT((uint32_t)(&(GPIO->PIMA)),26)
#define PIMA_P33 BIT_POINT((uint32_t)(&(GPIO->PIMA)),27)
#define PIMA_P34 BIT_POINT((uint32_t)(&(GPIO->PIMA)),28)
#define PIMA_P35 BIT_POINT((uint32_t)(&(GPIO->PIMA)),29)
#define PIMA_P36 BIT_POINT((uint32_t)(&(GPIO->PIMA)),30)
#define PIMA_P37 BIT_POINT((uint32_t)(&(GPIO->PIMA)),31)

//----------------------PIEA---------------------------
#define PIEA_P00 BIT_POINT((uint32_t)(&(GPIO->PIEA)),0)
#define PIEA_P01 BIT_POINT((uint32_t)(&(GPIO->PIEA)),1)
#define PIEA_P02 BIT_POINT((uint32_t)(&(GPIO->PIEA)),2)
#define PIEA_P03 BIT_POINT((uint32_t)(&(GPIO->PIEA)),3)
#define PIEA_P04 BIT_POINT((uint32_t)(&(GPIO->PIEA)),4)

#define PIEA_P10 BIT_POINT((uint32_t)(&(GPIO->PIEA)),8)
#define PIEA_P11 BIT_POINT((uint32_t)(&(GPIO->PIEA)),9)
#define PIEA_P12 BIT_POINT((uint32_t)(&(GPIO->PIEA)),10)
#define PIEA_P13 BIT_POINT((uint32_t)(&(GPIO->PIEA)),11)
#define PIEA_P14 BIT_POINT((uint32_t)(&(GPIO->PIEA)),12)
#define PIEA_P15 BIT_POINT((uint32_t)(&(GPIO->PIEA)),13)
#define PIEA_P16 BIT_POINT((uint32_t)(&(GPIO->PIEA)),14)
#define PIEA_P17 BIT_POINT((uint32_t)(&(GPIO->PIEA)),15)

#define PIEA_P20 BIT_POINT((uint32_t)(&(GPIO->PIEA)),16)
#define PIEA_P21 BIT_POINT((uint32_t)(&(GPIO->PIEA)),17)
#define PIEA_P22 BIT_POINT((uint32_t)(&(GPIO->PIEA)),18)
#define PIEA_P23 BIT_POINT((uint32_t)(&(GPIO->PIEA)),19)
#define PIEA_P24 BIT_POINT((uint32_t)(&(GPIO->PIEA)),20)
#define PIEA_P25 BIT_POINT((uint32_t)(&(GPIO->PIEA)),21)
#define PIEA_P26 BIT_POINT((uint32_t)(&(GPIO->PIEA)),22)
#define PIEA_P27 BIT_POINT((uint32_t)(&(GPIO->PIEA)),23)

#define PIEA_P30 BIT_POINT((uint32_t)(&(GPIO->PIEA)),24)
#define PIEA_P31 BIT_POINT((uint32_t)(&(GPIO->PIEA)),25)
#define PIEA_P32 BIT_POINT((uint32_t)(&(GPIO->PIEA)),26)
#define PIEA_P33 BIT_POINT((uint32_t)(&(GPIO->PIEA)),27)
#define PIEA_P34 BIT_POINT((uint32_t)(&(GPIO->PIEA)),28)
#define PIEA_P35 BIT_POINT((uint32_t)(&(GPIO->PIEA)),29)
#define PIEA_P36 BIT_POINT((uint32_t)(&(GPIO->PIEA)),30)
#define PIEA_P37 BIT_POINT((uint32_t)(&(GPIO->PIEA)),31)

//-----------------------PMB----------------------------
#define PMB_P40 BIT_POINT((uint32_t)(&(GPIO->PMB)),0)
#define PMB_P41 BIT_POINT((uint32_t)(&(GPIO->PMB)),1)
#define PMB_P42 BIT_POINT((uint32_t)(&(GPIO->PMB)),2)
#define PMB_P43 BIT_POINT((uint32_t)(&(GPIO->PMB)),3)
#define PMB_P44 BIT_POINT((uint32_t)(&(GPIO->PMB)),4)
#define PMB_P45 BIT_POINT((uint32_t)(&(GPIO->PMB)),5)
#define PMB_P46 BIT_POINT((uint32_t)(&(GPIO->PMB)),6)
#define PMB_P47 BIT_POINT((uint32_t)(&(GPIO->PMB)),7)

#define PMB_P50 BIT_POINT((uint32_t)(&(GPIO->PMB)),8)
#define PMB_P51 BIT_POINT((uint32_t)(&(GPIO->PMB)),9)
#define PMB_P52 BIT_POINT((uint32_t)(&(GPIO->PMB)),10)
#define PMB_P53 BIT_POINT((uint32_t)(&(GPIO->PMB)),11)
#define PMB_P54 BIT_POINT((uint32_t)(&(GPIO->PMB)),12)
#define PMB_P55 BIT_POINT((uint32_t)(&(GPIO->PMB)),13)
#define PMB_P56 BIT_POINT((uint32_t)(&(GPIO->PMB)),14)
#define PMB_P57 BIT_POINT((uint32_t)(&(GPIO->PMB)),15)

#define PMB_P60 BIT_POINT((uint32_t)(&(GPIO->PMB)),16)
#define PMB_P61 BIT_POINT((uint32_t)(&(GPIO->PMB)),17)
#define PMB_P62 BIT_POINT((uint32_t)(&(GPIO->PMB)),18)
#define PMB_P63 BIT_POINT((uint32_t)(&(GPIO->PMB)),19)
#define PMB_P64 BIT_POINT((uint32_t)(&(GPIO->PMB)),20)
#define PMB_P65 BIT_POINT((uint32_t)(&(GPIO->PMB)),21)
#define PMB_P66 BIT_POINT((uint32_t)(&(GPIO->PMB)),22)
#define PMB_P67 BIT_POINT((uint32_t)(&(GPIO->PMB)),23)

#define PMB_P70 BIT_POINT((uint32_t)(&(GPIO->PMB)),24)
#define PMB_P71 BIT_POINT((uint32_t)(&(GPIO->PMB)),25)
#define PMB_P72 BIT_POINT((uint32_t)(&(GPIO->PMB)),26)
#define PMB_P73 BIT_POINT((uint32_t)(&(GPIO->PMB)),27)
#define PMB_P74 BIT_POINT((uint32_t)(&(GPIO->PMB)),28)
#define PMB_P75 BIT_POINT((uint32_t)(&(GPIO->PMB)),29)
#define PMB_P76 BIT_POINT((uint32_t)(&(GPIO->PMB)),30)
#define PMB_P77 BIT_POINT((uint32_t)(&(GPIO->PMB)),31)

//-----------------------PB----------------------------
#define PB_P40 BIT_POINT((uint32_t)(&(GPIO->PB)),0)
#define PB_P41 BIT_POINT((uint32_t)(&(GPIO->PB)),1)
#define PB_P42 BIT_POINT((uint32_t)(&(GPIO->PB)),2)
#define PB_P43 BIT_POINT((uint32_t)(&(GPIO->PB)),3)
#define PB_P44 BIT_POINT((uint32_t)(&(GPIO->PB)),4)
#define PB_P45 BIT_POINT((uint32_t)(&(GPIO->PB)),5)
#define PB_P46 BIT_POINT((uint32_t)(&(GPIO->PB)),6)
#define PB_P47 BIT_POINT((uint32_t)(&(GPIO->PB)),7)

#define PB_P50 BIT_POINT((uint32_t)(&(GPIO->PB)),8)
#define PB_P51 BIT_POINT((uint32_t)(&(GPIO->PB)),9)
#define PB_P52 BIT_POINT((uint32_t)(&(GPIO->PB)),10)
#define PB_P53 BIT_POINT((uint32_t)(&(GPIO->PB)),11)
#define PB_P54 BIT_POINT((uint32_t)(&(GPIO->PB)),12)
#define PB_P55 BIT_POINT((uint32_t)(&(GPIO->PB)),13)
#define PB_P56 BIT_POINT((uint32_t)(&(GPIO->PB)),14)
#define PB_P57 BIT_POINT((uint32_t)(&(GPIO->PB)),15)

#define PB_P60 BIT_POINT((uint32_t)(&(GPIO->PB)),16)
#define PB_P61 BIT_POINT((uint32_t)(&(GPIO->PB)),17)
#define PB_P62 BIT_POINT((uint32_t)(&(GPIO->PB)),18)
#define PB_P63 BIT_POINT((uint32_t)(&(GPIO->PB)),19)
#define PB_P64 BIT_POINT((uint32_t)(&(GPIO->PB)),20)
#define PB_P65 BIT_POINT((uint32_t)(&(GPIO->PB)),21)
#define PB_P66 BIT_POINT((uint32_t)(&(GPIO->PB)),22)
#define PB_P67 BIT_POINT((uint32_t)(&(GPIO->PB)),23)

#define PB_P70 BIT_POINT((uint32_t)(&(GPIO->PB)),24)
#define PB_P71 BIT_POINT((uint32_t)(&(GPIO->PB)),25)
#define PB_P72 BIT_POINT((uint32_t)(&(GPIO->PB)),26)
#define PB_P73 BIT_POINT((uint32_t)(&(GPIO->PB)),27)
#define PB_P74 BIT_POINT((uint32_t)(&(GPIO->PB)),28)
#define PB_P75 BIT_POINT((uint32_t)(&(GPIO->PB)),29)
#define PB_P76 BIT_POINT((uint32_t)(&(GPIO->PB)),30)
#define PB_P77 BIT_POINT((uint32_t)(&(GPIO->PB)),31)

//-----------------------PCB---------------------------
#define PCB_P40 BIT_POINT((uint32_t)(&(GPIO->PCB)),0)
#define PCB_P41 BIT_POINT((uint32_t)(&(GPIO->PCB)),1)
#define PCB_P42 BIT_POINT((uint32_t)(&(GPIO->PCB)),2)
#define PCB_P43 BIT_POINT((uint32_t)(&(GPIO->PCB)),3)
#define PCB_P44 BIT_POINT((uint32_t)(&(GPIO->PCB)),4)
#define PCB_P45 BIT_POINT((uint32_t)(&(GPIO->PCB)),5)
#define PCB_P46 BIT_POINT((uint32_t)(&(GPIO->PCB)),6)
#define PCB_P47 BIT_POINT((uint32_t)(&(GPIO->PCB)),7)

#define PCB_P50 BIT_POINT((uint32_t)(&(GPIO->PCB)),8)
#define PCB_P51 BIT_POINT((uint32_t)(&(GPIO->PCB)),9)
#define PCB_P52 BIT_POINT((uint32_t)(&(GPIO->PCB)),10)
#define PCB_P53 BIT_POINT((uint32_t)(&(GPIO->PCB)),11)
#define PCB_P54 BIT_POINT((uint32_t)(&(GPIO->PCB)),12)
#define PCB_P55 BIT_POINT((uint32_t)(&(GPIO->PCB)),13)
#define PCB_P56 BIT_POINT((uint32_t)(&(GPIO->PCB)),14)
#define PCB_P57 BIT_POINT((uint32_t)(&(GPIO->PCB)),15)

#define PCB_P60 BIT_POINT((uint32_t)(&(GPIO->PCB)),16)
#define PCB_P61 BIT_POINT((uint32_t)(&(GPIO->PCB)),17)
#define PCB_P62 BIT_POINT((uint32_t)(&(GPIO->PCB)),18)
#define PCB_P63 BIT_POINT((uint32_t)(&(GPIO->PCB)),19)
#define PCB_P64 BIT_POINT((uint32_t)(&(GPIO->PCB)),20)
#define PCB_P65 BIT_POINT((uint32_t)(&(GPIO->PCB)),21)
#define PCB_P66 BIT_POINT((uint32_t)(&(GPIO->PCB)),22)
#define PCB_P67 BIT_POINT((uint32_t)(&(GPIO->PCB)),23)

#define PCB_P70 BIT_POINT((uint32_t)(&(GPIO->PCB)),24)
#define PCB_P71 BIT_POINT((uint32_t)(&(GPIO->PCB)),25)
#define PCB_P72 BIT_POINT((uint32_t)(&(GPIO->PCB)),26)
#define PCB_P73 BIT_POINT((uint32_t)(&(GPIO->PCB)),27)
#define PCB_P74 BIT_POINT((uint32_t)(&(GPIO->PCB)),28)
#define PCB_P75 BIT_POINT((uint32_t)(&(GPIO->PCB)),29)
#define PCB_P76 BIT_POINT((uint32_t)(&(GPIO->PCB)),30)
#define PCB_P77 BIT_POINT((uint32_t)(&(GPIO->PCB)),31)

//-----------------------PCB2---------------------------
#define PCB2_P40 BIT_POINT((uint32_t)(&(GPIO->PCB2)),0)
#define PCB2_P41 BIT_POINT((uint32_t)(&(GPIO->PCB2)),1)
#define PCB2_P42 BIT_POINT((uint32_t)(&(GPIO->PCB2)),2)
#define PCB2_P43 BIT_POINT((uint32_t)(&(GPIO->PCB2)),3)
#define PCB2_P44 BIT_POINT((uint32_t)(&(GPIO->PCB2)),4)
#define PCB2_P45 BIT_POINT((uint32_t)(&(GPIO->PCB2)),5)
#define PCB2_P46 BIT_POINT((uint32_t)(&(GPIO->PCB2)),6)
#define PCB2_P47 BIT_POINT((uint32_t)(&(GPIO->PCB2)),7)

#define PCB2_P50 BIT_POINT((uint32_t)(&(GPIO->PCB2)),8)
#define PCB2_P51 BIT_POINT((uint32_t)(&(GPIO->PCB2)),9)
#define PCB2_P52 BIT_POINT((uint32_t)(&(GPIO->PCB2)),10)
#define PCB2_P53 BIT_POINT((uint32_t)(&(GPIO->PCB2)),11)
#define PCB2_P54 BIT_POINT((uint32_t)(&(GPIO->PCB2)),12)
#define PCB2_P55 BIT_POINT((uint32_t)(&(GPIO->PCB2)),13)
#define PCB2_P56 BIT_POINT((uint32_t)(&(GPIO->PCB2)),14)
#define PCB2_P57 BIT_POINT((uint32_t)(&(GPIO->PCB2)),15)

#define PCB2_P60 BIT_POINT((uint32_t)(&(GPIO->PCB2)),16)
#define PCB2_P61 BIT_POINT((uint32_t)(&(GPIO->PCB2)),17)
#define PCB2_P62 BIT_POINT((uint32_t)(&(GPIO->PCB2)),18)
#define PCB2_P63 BIT_POINT((uint32_t)(&(GPIO->PCB2)),19)
#define PCB2_P64 BIT_POINT((uint32_t)(&(GPIO->PCB2)),20)
#define PCB2_P65 BIT_POINT((uint32_t)(&(GPIO->PCB2)),21)
#define PCB2_P66 BIT_POINT((uint32_t)(&(GPIO->PCB2)),22)
#define PCB2_P67 BIT_POINT((uint32_t)(&(GPIO->PCB2)),23)

#define PCB2_P70 BIT_POINT((uint32_t)(&(GPIO->PCB2)),24)
#define PCB2_P71 BIT_POINT((uint32_t)(&(GPIO->PCB2)),25)
#define PCB2_P72 BIT_POINT((uint32_t)(&(GPIO->PCB2)),26)
#define PCB2_P73 BIT_POINT((uint32_t)(&(GPIO->PCB2)),27)
#define PCB2_P74 BIT_POINT((uint32_t)(&(GPIO->PCB2)),28)
#define PCB2_P75 BIT_POINT((uint32_t)(&(GPIO->PCB2)),29)
#define PCB2_P76 BIT_POINT((uint32_t)(&(GPIO->PCB2)),30)
#define PCB2_P77 BIT_POINT((uint32_t)(&(GPIO->PCB2)),31)

//-----------------------PUB---------------------------
#define PUB_P40 BIT_POINT((uint32_t)(&(GPIO->PUB)),0)
#define PUB_P41 BIT_POINT((uint32_t)(&(GPIO->PUB)),1)
#define PUB_P42 BIT_POINT((uint32_t)(&(GPIO->PUB)),2)
#define PUB_P43 BIT_POINT((uint32_t)(&(GPIO->PUB)),3)
#define PUB_P44 BIT_POINT((uint32_t)(&(GPIO->PUB)),4)
#define PUB_P45 BIT_POINT((uint32_t)(&(GPIO->PUB)),5)
#define PUB_P46 BIT_POINT((uint32_t)(&(GPIO->PUB)),6)
#define PUB_P47 BIT_POINT((uint32_t)(&(GPIO->PUB)),7)

#define PUB_P50 BIT_POINT((uint32_t)(&(GPIO->PUB)),8)
#define PUB_P51 BIT_POINT((uint32_t)(&(GPIO->PUB)),9)
#define PUB_P52 BIT_POINT((uint32_t)(&(GPIO->PUB)),10)
#define PUB_P53 BIT_POINT((uint32_t)(&(GPIO->PUB)),11)
#define PUB_P54 BIT_POINT((uint32_t)(&(GPIO->PUB)),12)
#define PUB_P55 BIT_POINT((uint32_t)(&(GPIO->PUB)),13)
#define PUB_P56 BIT_POINT((uint32_t)(&(GPIO->PUB)),14)
#define PUB_P57 BIT_POINT((uint32_t)(&(GPIO->PUB)),15)

#define PUB_P60 BIT_POINT((uint32_t)(&(GPIO->PUB)),16)
#define PUB_P61 BIT_POINT((uint32_t)(&(GPIO->PUB)),17)
#define PUB_P62 BIT_POINT((uint32_t)(&(GPIO->PUB)),18)
#define PUB_P63 BIT_POINT((uint32_t)(&(GPIO->PUB)),19)
#define PUB_P64 BIT_POINT((uint32_t)(&(GPIO->PUB)),20)
#define PUB_P65 BIT_POINT((uint32_t)(&(GPIO->PUB)),21)
#define PUB_P66 BIT_POINT((uint32_t)(&(GPIO->PUB)),22)
#define PUB_P67 BIT_POINT((uint32_t)(&(GPIO->PUB)),23)

#define PUB_P70 BIT_POINT((uint32_t)(&(GPIO->PUB)),24)
#define PUB_P71 BIT_POINT((uint32_t)(&(GPIO->PUB)),25)
#define PUB_P72 BIT_POINT((uint32_t)(&(GPIO->PUB)),26)
#define PUB_P73 BIT_POINT((uint32_t)(&(GPIO->PUB)),27)
#define PUB_P74 BIT_POINT((uint32_t)(&(GPIO->PUB)),28)
#define PUB_P75 BIT_POINT((uint32_t)(&(GPIO->PUB)),29)
#define PUB_P76 BIT_POINT((uint32_t)(&(GPIO->PUB)),30)
#define PUB_P77 BIT_POINT((uint32_t)(&(GPIO->PUB)),31)

//-----------------------PIMB--------------------------
#define PIMB_P40 BIT_POINT((uint32_t)(&(GPIO->PIMB)),0)
#define PIMB_P41 BIT_POINT((uint32_t)(&(GPIO->PIMB)),1)
#define PIMB_P42 BIT_POINT((uint32_t)(&(GPIO->PIMB)),2)
#define PIMB_P43 BIT_POINT((uint32_t)(&(GPIO->PIMB)),3)
#define PIMB_P44 BIT_POINT((uint32_t)(&(GPIO->PIMB)),4)
#define PIMB_P45 BIT_POINT((uint32_t)(&(GPIO->PIMB)),5)
#define PIMB_P46 BIT_POINT((uint32_t)(&(GPIO->PIMB)),6)
#define PIMB_P47 BIT_POINT((uint32_t)(&(GPIO->PIMB)),7)

#define PIMB_P50 BIT_POINT((uint32_t)(&(GPIO->PIMB)),8)
#define PIMB_P51 BIT_POINT((uint32_t)(&(GPIO->PIMB)),9)
#define PIMB_P52 BIT_POINT((uint32_t)(&(GPIO->PIMB)),10)
#define PIMB_P53 BIT_POINT((uint32_t)(&(GPIO->PIMB)),11)
#define PIMB_P54 BIT_POINT((uint32_t)(&(GPIO->PIMB)),12)
#define PIMB_P55 BIT_POINT((uint32_t)(&(GPIO->PIMB)),13)
#define PIMB_P56 BIT_POINT((uint32_t)(&(GPIO->PIMB)),14)
#define PIMB_P57 BIT_POINT((uint32_t)(&(GPIO->PIMB)),15)

#define PIMB_P60 BIT_POINT((uint32_t)(&(GPIO->PIMB)),16)
#define PIMB_P61 BIT_POINT((uint32_t)(&(GPIO->PIMB)),17)
#define PIMB_P62 BIT_POINT((uint32_t)(&(GPIO->PIMB)),18)
#define PIMB_P63 BIT_POINT((uint32_t)(&(GPIO->PIMB)),19)
#define PIMB_P64 BIT_POINT((uint32_t)(&(GPIO->PIMB)),20)
#define PIMB_P65 BIT_POINT((uint32_t)(&(GPIO->PIMB)),21)
#define PIMB_P66 BIT_POINT((uint32_t)(&(GPIO->PIMB)),22)
#define PIMB_P67 BIT_POINT((uint32_t)(&(GPIO->PIMB)),23)

#define PIMB_P70 BIT_POINT((uint32_t)(&(GPIO->PIMB)),24)
#define PIMB_P71 BIT_POINT((uint32_t)(&(GPIO->PIMB)),25)
#define PIMB_P72 BIT_POINT((uint32_t)(&(GPIO->PIMB)),26)
#define PIMB_P73 BIT_POINT((uint32_t)(&(GPIO->PIMB)),27)
#define PIMB_P74 BIT_POINT((uint32_t)(&(GPIO->PIMB)),28)
#define PIMB_P75 BIT_POINT((uint32_t)(&(GPIO->PIMB)),29)
#define PIMB_P76 BIT_POINT((uint32_t)(&(GPIO->PIMB)),30)
#define PIMB_P77 BIT_POINT((uint32_t)(&(GPIO->PIMB)),31)

//-----------------------PIEB--------------------------
#define PIEB_P40 BIT_POINT((uint32_t)(&(GPIO->PIEB)),0)
#define PIEB_P41 BIT_POINT((uint32_t)(&(GPIO->PIEB)),1)
#define PIEB_P42 BIT_POINT((uint32_t)(&(GPIO->PIEB)),2)
#define PIEB_P43 BIT_POINT((uint32_t)(&(GPIO->PIEB)),3)
#define PIEB_P44 BIT_POINT((uint32_t)(&(GPIO->PIEB)),4)
#define PIEB_P45 BIT_POINT((uint32_t)(&(GPIO->PIEB)),5)
#define PIEB_P46 BIT_POINT((uint32_t)(&(GPIO->PIEB)),6)
#define PIEB_P47 BIT_POINT((uint32_t)(&(GPIO->PIEB)),7)

#define PIEB_P50 BIT_POINT((uint32_t)(&(GPIO->PIEB)),8)
#define PIEB_P51 BIT_POINT((uint32_t)(&(GPIO->PIEB)),9)
#define PIEB_P52 BIT_POINT((uint32_t)(&(GPIO->PIEB)),10)
#define PIEB_P53 BIT_POINT((uint32_t)(&(GPIO->PIEB)),11)
#define PIEB_P54 BIT_POINT((uint32_t)(&(GPIO->PIEB)),12)
#define PIEB_P55 BIT_POINT((uint32_t)(&(GPIO->PIEB)),13)
#define PIEB_P56 BIT_POINT((uint32_t)(&(GPIO->PIEB)),14)
#define PIEB_P57 BIT_POINT((uint32_t)(&(GPIO->PIEB)),15)

#define PIEB_P60 BIT_POINT((uint32_t)(&(GPIO->PIEB)),16)
#define PIEB_P61 BIT_POINT((uint32_t)(&(GPIO->PIEB)),17)
#define PIEB_P62 BIT_POINT((uint32_t)(&(GPIO->PIEB)),18)
#define PIEB_P63 BIT_POINT((uint32_t)(&(GPIO->PIEB)),19)
#define PIEB_P64 BIT_POINT((uint32_t)(&(GPIO->PIEB)),20)
#define PIEB_P65 BIT_POINT((uint32_t)(&(GPIO->PIEB)),21)
#define PIEB_P66 BIT_POINT((uint32_t)(&(GPIO->PIEB)),22)
#define PIEB_P67 BIT_POINT((uint32_t)(&(GPIO->PIEB)),23)

#define PIEB_P70 BIT_POINT((uint32_t)(&(GPIO->PIEB)),24)
#define PIEB_P71 BIT_POINT((uint32_t)(&(GPIO->PIEB)),25)
#define PIEB_P72 BIT_POINT((uint32_t)(&(GPIO->PIEB)),26)
#define PIEB_P73 BIT_POINT((uint32_t)(&(GPIO->PIEB)),27)
#define PIEB_P74 BIT_POINT((uint32_t)(&(GPIO->PIEB)),28)
#define PIEB_P75 BIT_POINT((uint32_t)(&(GPIO->PIEB)),29)
#define PIEB_P76 BIT_POINT((uint32_t)(&(GPIO->PIEB)),30)
#define PIEB_P77 BIT_POINT((uint32_t)(&(GPIO->PIEB)),31)

//-----------------------PMC---------------------------
#define PMC_P80 BIT_POINT((uint32_t)(&(GPIO->PMC)),0)
#define PMC_P81 BIT_POINT((uint32_t)(&(GPIO->PMC)),1)
#define PMC_P82 BIT_POINT((uint32_t)(&(GPIO->PMC)),2)
#define PMC_P83 BIT_POINT((uint32_t)(&(GPIO->PMC)),3)
#define PMC_P84 BIT_POINT((uint32_t)(&(GPIO->PMC)),4)
#define PMC_P85 BIT_POINT((uint32_t)(&(GPIO->PMC)),5)
#define PMC_P86 BIT_POINT((uint32_t)(&(GPIO->PMC)),6)
#define PMC_P87 BIT_POINT((uint32_t)(&(GPIO->PMC)),7)

#define PMC_P90 BIT_POINT((uint32_t)(&(GPIO->PMC)),8)
#define PMC_P91 BIT_POINT((uint32_t)(&(GPIO->PMC)),9)
#define PMC_P92 BIT_POINT((uint32_t)(&(GPIO->PMC)),10)
#define PMC_P93 BIT_POINT((uint32_t)(&(GPIO->PMC)),11)
#define PMC_P94 BIT_POINT((uint32_t)(&(GPIO->PMC)),12)
#define PMC_P95 BIT_POINT((uint32_t)(&(GPIO->PMC)),13)
#define PMC_P96 BIT_POINT((uint32_t)(&(GPIO->PMC)),14)
#define PMC_P97 BIT_POINT((uint32_t)(&(GPIO->PMC)),15)

#define PMC_P100 BIT_POINT((uint32_t)(&(GPIO->PMC)),16)
#define PMC_P101 BIT_POINT((uint32_t)(&(GPIO->PMC)),17)
#define PMC_P102 BIT_POINT((uint32_t)(&(GPIO->PMC)),18)
#define PMC_P103 BIT_POINT((uint32_t)(&(GPIO->PMC)),19)
#define PMC_P104 BIT_POINT((uint32_t)(&(GPIO->PMC)),20)
#define PMC_P105 BIT_POINT((uint32_t)(&(GPIO->PMC)),21)
#define PMC_P106 BIT_POINT((uint32_t)(&(GPIO->PMC)),22)
#define PMC_P107 BIT_POINT((uint32_t)(&(GPIO->PMC)),23)

#define PMC_P110 BIT_POINT((uint32_t)(&(GPIO->PMC)),24)
#define PMC_P111 BIT_POINT((uint32_t)(&(GPIO->PMC)),25)
#define PMC_P112 BIT_POINT((uint32_t)(&(GPIO->PMC)),26)
#define PMC_P113 BIT_POINT((uint32_t)(&(GPIO->PMC)),27)
#define PMC_P114 BIT_POINT((uint32_t)(&(GPIO->PMC)),28)
#define PMC_P115 BIT_POINT((uint32_t)(&(GPIO->PMC)),29)
#define PMC_P116 BIT_POINT((uint32_t)(&(GPIO->PMC)),30)
#define PMC_P117 BIT_POINT((uint32_t)(&(GPIO->PMC)),31)

//-----------------------PC---------------------------
#define PC_P80 BIT_POINT((uint32_t)(&(GPIO->PC)),0)
#define PC_P81 BIT_POINT((uint32_t)(&(GPIO->PC)),1)
#define PC_P82 BIT_POINT((uint32_t)(&(GPIO->PC)),2)
#define PC_P83 BIT_POINT((uint32_t)(&(GPIO->PC)),3)
#define PC_P84 BIT_POINT((uint32_t)(&(GPIO->PC)),4)
#define PC_P85 BIT_POINT((uint32_t)(&(GPIO->PC)),5)
#define PC_P86 BIT_POINT((uint32_t)(&(GPIO->PC)),6)
#define PC_P87 BIT_POINT((uint32_t)(&(GPIO->PC)),7)

#define PC_P90 BIT_POINT((uint32_t)(&(GPIO->PC)),8)
#define PC_P91 BIT_POINT((uint32_t)(&(GPIO->PC)),9)
#define PC_P92 BIT_POINT((uint32_t)(&(GPIO->PC)),10)
#define PC_P93 BIT_POINT((uint32_t)(&(GPIO->PC)),11)
#define PC_P94 BIT_POINT((uint32_t)(&(GPIO->PC)),12)
#define PC_P95 BIT_POINT((uint32_t)(&(GPIO->PC)),13)
#define PC_P96 BIT_POINT((uint32_t)(&(GPIO->PC)),14)
#define PC_P97 BIT_POINT((uint32_t)(&(GPIO->PC)),15)

#define PC_P100 BIT_POINT((uint32_t)(&(GPIO->PC)),16)
#define PC_P101 BIT_POINT((uint32_t)(&(GPIO->PC)),17)
#define PC_P102 BIT_POINT((uint32_t)(&(GPIO->PC)),18)
#define PC_P103 BIT_POINT((uint32_t)(&(GPIO->PC)),19)
#define PC_P104 BIT_POINT((uint32_t)(&(GPIO->PC)),20)
#define PC_P105 BIT_POINT((uint32_t)(&(GPIO->PC)),21)
#define PC_P106 BIT_POINT((uint32_t)(&(GPIO->PC)),22)
#define PC_P107 BIT_POINT((uint32_t)(&(GPIO->PC)),23)

#define PC_P110 BIT_POINT((uint32_t)(&(GPIO->PC)),24)
#define PC_P111 BIT_POINT((uint32_t)(&(GPIO->PC)),25)
#define PC_P112 BIT_POINT((uint32_t)(&(GPIO->PC)),26)
#define PC_P113 BIT_POINT((uint32_t)(&(GPIO->PC)),27)
#define PC_P114 BIT_POINT((uint32_t)(&(GPIO->PC)),28)
#define PC_P115 BIT_POINT((uint32_t)(&(GPIO->PC)),29)
#define PC_P116 BIT_POINT((uint32_t)(&(GPIO->PC)),30)
#define PC_P117 BIT_POINT((uint32_t)(&(GPIO->PC)),31)

//-----------------------PCC---------------------------
#define PCC_P80 BIT_POINT((uint32_t)(&(GPIO->PCC)),0)
#define PCC_P81 BIT_POINT((uint32_t)(&(GPIO->PCC)),1)
#define PCC_P82 BIT_POINT((uint32_t)(&(GPIO->PCC)),2)
#define PCC_P83 BIT_POINT((uint32_t)(&(GPIO->PCC)),3)
#define PCC_P84 BIT_POINT((uint32_t)(&(GPIO->PCC)),4)
#define PCC_P85 BIT_POINT((uint32_t)(&(GPIO->PCC)),5)
#define PCC_P86 BIT_POINT((uint32_t)(&(GPIO->PCC)),6)
#define PCC_P87 BIT_POINT((uint32_t)(&(GPIO->PCC)),7)

#define PCC_P90 BIT_POINT((uint32_t)(&(GPIO->PCC)),8)
#define PCC_P91 BIT_POINT((uint32_t)(&(GPIO->PCC)),9)
#define PCC_P92 BIT_POINT((uint32_t)(&(GPIO->PCC)),10)
#define PCC_P93 BIT_POINT((uint32_t)(&(GPIO->PCC)),11)
#define PCC_P94 BIT_POINT((uint32_t)(&(GPIO->PCC)),12)
#define PCC_P95 BIT_POINT((uint32_t)(&(GPIO->PCC)),13)
#define PCC_P96 BIT_POINT((uint32_t)(&(GPIO->PCC)),14)
#define PCC_P97 BIT_POINT((uint32_t)(&(GPIO->PCC)),15)

#define PCC_P100 BIT_POINT((uint32_t)(&(GPIO->PCC)),16)
#define PCC_P101 BIT_POINT((uint32_t)(&(GPIO->PCC)),17)
#define PCC_P102 BIT_POINT((uint32_t)(&(GPIO->PCC)),18)
#define PCC_P103 BIT_POINT((uint32_t)(&(GPIO->PCC)),19)
#define PCC_P104 BIT_POINT((uint32_t)(&(GPIO->PCC)),20)
#define PCC_P105 BIT_POINT((uint32_t)(&(GPIO->PCC)),21)
#define PCC_P106 BIT_POINT((uint32_t)(&(GPIO->PCC)),22)
#define PCC_P107 BIT_POINT((uint32_t)(&(GPIO->PCC)),23)

#define PCC_P110 BIT_POINT((uint32_t)(&(GPIO->PCC)),24)
#define PCC_P111 BIT_POINT((uint32_t)(&(GPIO->PCC)),25)
#define PCC_P112 BIT_POINT((uint32_t)(&(GPIO->PCC)),26)
#define PCC_P113 BIT_POINT((uint32_t)(&(GPIO->PCC)),27)
#define PCC_P114 BIT_POINT((uint32_t)(&(GPIO->PCC)),28)
#define PCC_P115 BIT_POINT((uint32_t)(&(GPIO->PCC)),29)
#define PCC_P116 BIT_POINT((uint32_t)(&(GPIO->PCC)),30)
#define PCC_P117 BIT_POINT((uint32_t)(&(GPIO->PCC)),31)

//-----------------------PUC---------------------------
#define PUC_P80 BIT_POINT((uint32_t)(&(GPIO->PUC)),0)
#define PUC_P81 BIT_POINT((uint32_t)(&(GPIO->PUC)),1)
#define PUC_P82 BIT_POINT((uint32_t)(&(GPIO->PUC)),2)
#define PUC_P83 BIT_POINT((uint32_t)(&(GPIO->PUC)),3)
#define PUC_P84 BIT_POINT((uint32_t)(&(GPIO->PUC)),4)
#define PUC_P85 BIT_POINT((uint32_t)(&(GPIO->PUC)),5)
#define PUC_P86 BIT_POINT((uint32_t)(&(GPIO->PUC)),6)
#define PUC_P87 BIT_POINT((uint32_t)(&(GPIO->PUC)),7)

#define PUC_P90 BIT_POINT((uint32_t)(&(GPIO->PUC)),8)
#define PUC_P91 BIT_POINT((uint32_t)(&(GPIO->PUC)),9)
#define PUC_P92 BIT_POINT((uint32_t)(&(GPIO->PUC)),10)
#define PUC_P93 BIT_POINT((uint32_t)(&(GPIO->PUC)),11)
#define PUC_P94 BIT_POINT((uint32_t)(&(GPIO->PUC)),12)
#define PUC_P95 BIT_POINT((uint32_t)(&(GPIO->PUC)),13)
#define PUC_P96 BIT_POINT((uint32_t)(&(GPIO->PUC)),14)
#define PUC_P97 BIT_POINT((uint32_t)(&(GPIO->PUC)),15)

#define PUC_P100 BIT_POINT((uint32_t)(&(GPIO->PUC)),16)
#define PUC_P101 BIT_POINT((uint32_t)(&(GPIO->PUC)),17)
#define PUC_P102 BIT_POINT((uint32_t)(&(GPIO->PUC)),18)
#define PUC_P103 BIT_POINT((uint32_t)(&(GPIO->PUC)),19)
#define PUC_P104 BIT_POINT((uint32_t)(&(GPIO->PUC)),20)
#define PUC_P105 BIT_POINT((uint32_t)(&(GPIO->PUC)),21)
#define PUC_P106 BIT_POINT((uint32_t)(&(GPIO->PUC)),22)
#define PUC_P107 BIT_POINT((uint32_t)(&(GPIO->PUC)),23)

#define PUC_P110 BIT_POINT((uint32_t)(&(GPIO->PUC)),24)
#define PUC_P111 BIT_POINT((uint32_t)(&(GPIO->PUC)),25)
#define PUC_P112 BIT_POINT((uint32_t)(&(GPIO->PUC)),26)
#define PUC_P113 BIT_POINT((uint32_t)(&(GPIO->PUC)),27)
#define PUC_P114 BIT_POINT((uint32_t)(&(GPIO->PUC)),28)
#define PUC_P115 BIT_POINT((uint32_t)(&(GPIO->PUC)),29)
#define PUC_P116 BIT_POINT((uint32_t)(&(GPIO->PUC)),30)
#define PUC_P117 BIT_POINT((uint32_t)(&(GPIO->PUC)),31)

//-----------------------PIEC---------------------------
#define PIEC_P80 BIT_POINT((uint32_t)(&(GPIO->PIEC)),0)
#define PIEC_P81 BIT_POINT((uint32_t)(&(GPIO->PIEC)),1)
#define PIEC_P82 BIT_POINT((uint32_t)(&(GPIO->PIEC)),2)
#define PIEC_P83 BIT_POINT((uint32_t)(&(GPIO->PIEC)),3)
#define PIEC_P84 BIT_POINT((uint32_t)(&(GPIO->PIEC)),4)
#define PIEC_P85 BIT_POINT((uint32_t)(&(GPIO->PIEC)),5)
#define PIEC_P86 BIT_POINT((uint32_t)(&(GPIO->PIEC)),6)
#define PIEC_P87 BIT_POINT((uint32_t)(&(GPIO->PIEC)),7)

#define PIEC_P90 BIT_POINT((uint32_t)(&(GPIO->PIEC)),8)
#define PIEC_P91 BIT_POINT((uint32_t)(&(GPIO->PIEC)),9)
#define PIEC_P92 BIT_POINT((uint32_t)(&(GPIO->PIEC)),10)
#define PIEC_P93 BIT_POINT((uint32_t)(&(GPIO->PIEC)),11)
#define PIEC_P94 BIT_POINT((uint32_t)(&(GPIO->PIEC)),12)
#define PIEC_P95 BIT_POINT((uint32_t)(&(GPIO->PIEC)),13)
#define PIEC_P96 BIT_POINT((uint32_t)(&(GPIO->PIEC)),14)
#define PIEC_P97 BIT_POINT((uint32_t)(&(GPIO->PIEC)),15)

#define PIEC_P100 BIT_POINT((uint32_t)(&(GPIO->PIEC)),16)
#define PIEC_P101 BIT_POINT((uint32_t)(&(GPIO->PIEC)),17)
#define PIEC_P102 BIT_POINT((uint32_t)(&(GPIO->PIEC)),18)
#define PIEC_P103 BIT_POINT((uint32_t)(&(GPIO->PIEC)),19)
#define PIEC_P104 BIT_POINT((uint32_t)(&(GPIO->PIEC)),20)
#define PIEC_P105 BIT_POINT((uint32_t)(&(GPIO->PIEC)),21)
#define PIEC_P106 BIT_POINT((uint32_t)(&(GPIO->PIEC)),22)
#define PIEC_P107 BIT_POINT((uint32_t)(&(GPIO->PIEC)),23)

#define PIEC_P110 BIT_POINT((uint32_t)(&(GPIO->PIEC)),24)
#define PIEC_P111 BIT_POINT((uint32_t)(&(GPIO->PIEC)),25)
#define PIEC_P112 BIT_POINT((uint32_t)(&(GPIO->PIEC)),26)
#define PIEC_P113 BIT_POINT((uint32_t)(&(GPIO->PIEC)),27)
#define PIEC_P114 BIT_POINT((uint32_t)(&(GPIO->PIEC)),28)
#define PIEC_P115 BIT_POINT((uint32_t)(&(GPIO->PIEC)),29)
#define PIEC_P116 BIT_POINT((uint32_t)(&(GPIO->PIEC)),30)
#define PIEC_P117 BIT_POINT((uint32_t)(&(GPIO->PIEC)),31)

//-----------------------PIMC---------------------------
#define PIMC_P80 BIT_POINT((uint32_t)(&(GPIO->PIMC)),0)
#define PIMC_P81 BIT_POINT((uint32_t)(&(GPIO->PIMC)),1)
#define PIMC_P82 BIT_POINT((uint32_t)(&(GPIO->PIMC)),2)
#define PIMC_P83 BIT_POINT((uint32_t)(&(GPIO->PIMC)),3)
#define PIMC_P84 BIT_POINT((uint32_t)(&(GPIO->PIMC)),4)
#define PIMC_P85 BIT_POINT((uint32_t)(&(GPIO->PIMC)),5)
#define PIMC_P86 BIT_POINT((uint32_t)(&(GPIO->PIMC)),6)
#define PIMC_P87 BIT_POINT((uint32_t)(&(GPIO->PIMC)),7)

#define PIMC_P90 BIT_POINT((uint32_t)(&(GPIO->PIMC)),8)
#define PIMC_P91 BIT_POINT((uint32_t)(&(GPIO->PIMC)),9)
#define PIMC_P92 BIT_POINT((uint32_t)(&(GPIO->PIMC)),10)
#define PIMC_P93 BIT_POINT((uint32_t)(&(GPIO->PIMC)),11)
#define PIMC_P94 BIT_POINT((uint32_t)(&(GPIO->PIMC)),12)
#define PIMC_P95 BIT_POINT((uint32_t)(&(GPIO->PIMC)),13)
#define PIMC_P96 BIT_POINT((uint32_t)(&(GPIO->PIMC)),14)
#define PIMC_P97 BIT_POINT((uint32_t)(&(GPIO->PIMC)),15)

#define PIMC_P100 BIT_POINT((uint32_t)(&(GPIO->PIMC)),16)
#define PIMC_P101 BIT_POINT((uint32_t)(&(GPIO->PIMC)),17)
#define PIMC_P102 BIT_POINT((uint32_t)(&(GPIO->PIMC)),18)
#define PIMC_P103 BIT_POINT((uint32_t)(&(GPIO->PIMC)),19)
#define PIMC_P104 BIT_POINT((uint32_t)(&(GPIO->PIMC)),20)
#define PIMC_P105 BIT_POINT((uint32_t)(&(GPIO->PIMC)),21)
#define PIMC_P106 BIT_POINT((uint32_t)(&(GPIO->PIMC)),22)
#define PIMC_P107 BIT_POINT((uint32_t)(&(GPIO->PIMC)),23)

#define PIMC_P110 BIT_POINT((uint32_t)(&(GPIO->PIMC)),24)
#define PIMC_P111 BIT_POINT((uint32_t)(&(GPIO->PIMC)),25)
#define PIMC_P112 BIT_POINT((uint32_t)(&(GPIO->PIMC)),26)
#define PIMC_P113 BIT_POINT((uint32_t)(&(GPIO->PIMC)),27)
#define PIMC_P114 BIT_POINT((uint32_t)(&(GPIO->PIMC)),28)
#define PIMC_P115 BIT_POINT((uint32_t)(&(GPIO->PIMC)),29)
#define PIMC_P116 BIT_POINT((uint32_t)(&(GPIO->PIMC)),30)
#define PIMC_P117 BIT_POINT((uint32_t)(&(GPIO->PIMC)),31)

//-----------------------EMUCON--------------------------
#define EMUCON_PRUN BIT_POINT((uint32_t)(&(EMU->EMUCON)),0)
#define EMUCON_QRUN BIT_POINT((uint32_t)(&(EMU->EMUCON)),1)
#define EMUCON_SRUN BIT_POINT((uint32_t)(&(EMU->EMUCON)),2)
#define EMUCON_CFSU0 BIT_POINT((uint32_t)(&(EMU->EMUCON)),3)
#define EMUCON_CFSU1 BIT_POINT((uint32_t)(&(EMU->EMUCON)),4)
#define EMUCON_CFSUEN BIT_POINT((uint32_t)(&(EMU->EMUCON)),5)
#define EMUCON_HPFUOFF BIT_POINT((uint32_t)(&(EMU->EMUCON)),6)
#define EMUCON_HPFIAOFF BIT_POINT((uint32_t)(&(EMU->EMUCON)),7)
#define EMUCON_HPFIBOFF BIT_POINT((uint32_t)(&(EMU->EMUCON)),8)
#define EMUCON_ENERGY_CLR BIT_POINT((uint32_t)(&(EMU->EMUCON)),9)
#define EMUCON_ZXD0 BIT_POINT((uint32_t)(&(EMU->EMUCON)),10)
#define EMUCON_ZXD1 BIT_POINT((uint32_t)(&(EMU->EMUCON)),11)
#define EMUCON_PMOD0 BIT_POINT((uint32_t)(&(EMU->EMUCON)),12)
#define EMUCON_PMOD1 BIT_POINT((uint32_t)(&(EMU->EMUCON)),13)
#define EMUCON_QMOD0 BIT_POINT((uint32_t)(&(EMU->EMUCON)),14)
#define EMUCON_QMOD1 BIT_POINT((uint32_t)(&(EMU->EMUCON)),15)
#define EMUCON_USTART BIT_POINT((uint32_t)(&(EMU->EMUCON)),16)
#define EMUCON_CF3_CFG BIT_POINT((uint32_t)(&(EMU->EMUCON)),17)
#define EMUCON_P2RUN BIT_POINT((uint32_t)(&(EMU->EMUCON)),18)
#define EMUCON_Q2RUN BIT_POINT((uint32_t)(&(EMU->EMUCON)),19)
#define EMUCON_S2RUN BIT_POINT((uint32_t)(&(EMU->EMUCON)),20)

//-----------------------EMUCON2--------------------------
#define EMUCON2_IADC_EN BIT_POINT((uint32_t)(&(EMU->EMUCON2)),0)
#define EMUCON2_IBDC_EN BIT_POINT((uint32_t)(&(EMU->EMUCON2)),1)
#define EMUCON2_UDC_EN BIT_POINT((uint32_t)(&(EMU->EMUCON2)),2)
#define EMUCON2_CF1_CFG0 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),11)
#define EMUCON2_CF1_CFG1 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),12)
#define EMUCON2_CF2_CFG0 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),13)
#define EMUCON2_CF2_CFG1 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),14)
#define EMUCON2_PADD0 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),15)
#define EMUCON2_PADD1 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),16)
#define EMUCON2_PADD2 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),17)
#define EMUCON2_QADD0 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),18)
#define EMUCON2_QADD1 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),19)
#define EMUCON2_QADD2 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),20)
#define EMUCON2_SADD0 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),21)
#define EMUCON2_SADD1 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),22)
#define EMUCON2_SADD2 BIT_POINT((uint32_t)(&(EMU->EMUCON2)),23)

//-----------------------EMU->IE--------------------------
#define EMUIE_DUPD BIT_POINT((uint32_t)(&(EMU->IE)),0)
#define EMUIE_PF BIT_POINT((uint32_t)(&(EMU->IE)),1)
#define EMUIE_QF BIT_POINT((uint32_t)(&(EMU->IE)),2)
#define EMUIE_PEO BIT_POINT((uint32_t)(&(EMU->IE)),3)
#define EMUIE_QEO BIT_POINT((uint32_t)(&(EMU->IE)),4)
#define EMUIE_ZX BIT_POINT((uint32_t)(&(EMU->IE)),5)
#define EMUIE_IBPEAK BIT_POINT((uint32_t)(&(EMU->IE)),6)
#define EMUIE_IAPEAK BIT_POINT((uint32_t)(&(EMU->IE)),7)
#define EMUIE_UPEAK BIT_POINT((uint32_t)(&(EMU->IE)),8)
#define EMUIE_UPSAG BIT_POINT((uint32_t)(&(EMU->IE)),9)
#define EMUIE_SPL BIT_POINT((uint32_t)(&(EMU->IE)),10)
#define EMUIE_LDO BIT_POINT((uint32_t)(&(EMU->IE)),11)
#define EMUIE_VREF BIT_POINT((uint32_t)(&(EMU->IE)),12)
#define EMUIE_SEO BIT_POINT((uint32_t)(&(EMU->IE)),13)
#define EMUIE_SF BIT_POINT((uint32_t)(&(EMU->IE)),14)
#define EMUIE_PF2 BIT_POINT((uint32_t)(&(EMU->IE)),15)
#define EMUIE_QF2 BIT_POINT((uint32_t)(&(EMU->IE)),16)
#define EMUIE_SF2 BIT_POINT((uint32_t)(&(EMU->IE)),17)
#define EMUIE_P2 BIT_POINT((uint32_t)(&(EMU->IE)),18)
#define EMUIE_Q2 BIT_POINT((uint32_t)(&(EMU->IE)),19)
#define EMUIE_S2 BIT_POINT((uint32_t)(&(EMU->IE)),20)
#define EMUIE_UZ BIT_POINT((uint32_t)(&(EMU->IE)),21)
#define EMUIE_I1Z BIT_POINT((uint32_t)(&(EMU->IE)),22)
#define EMUIE_I2Z BIT_POINT((uint32_t)(&(EMU->IE)),23)

//-----------------------EMU->IF------------------------
#define EMUIF_DUPD BIT_POINT((uint32_t)(&(EMU->IF)),0)
#define EMUIF_PF BIT_POINT((uint32_t)(&(EMU->IF)),1)
#define EMUIF_QF BIT_POINT((uint32_t)(&(EMU->IF)),2)
#define EMUIF_PEO BIT_POINT((uint32_t)(&(EMU->IF)),3)
#define EMUIF_QEO BIT_POINT((uint32_t)(&(EMU->IF)),4)
#define EMUIF_ZX BIT_POINT((uint32_t)(&(EMU->IF)),5)
#define EMUIF_IBPEAK BIT_POINT((uint32_t)(&(EMU->IF)),6)
#define EMUIF_IAPEAK BIT_POINT((uint32_t)(&(EMU->IF)),7)
#define EMUIF_UPEAK BIT_POINT((uint32_t)(&(EMU->IF)),8)
#define EMUIF_UPSAG BIT_POINT((uint32_t)(&(EMU->IF)),9)
#define EMUIF_SPL BIT_POINT((uint32_t)(&(EMU->IF)),10)
#define EMUIF_LDO BIT_POINT((uint32_t)(&(EMU->IF)),11)
#define EMUIF_VREF BIT_POINT((uint32_t)(&(EMU->IF)),12)
#define EMUIF_SEO BIT_POINT((uint32_t)(&(EMU->IF)),13)
#define EMUIF_SF BIT_POINT((uint32_t)(&(EMU->IF)),14)
#define EMUIF_PF2 BIT_POINT((uint32_t)(&(EMU->IF)),15)
#define EMUIF_QF2 BIT_POINT((uint32_t)(&(EMU->IF)),16)
#define EMUIF_SF2 BIT_POINT((uint32_t)(&(EMU->IF)),17)
#define EMUIF_P2 BIT_POINT((uint32_t)(&(EMU->IF)),18)
#define EMUIF_Q2 BIT_POINT((uint32_t)(&(EMU->IF)),19)
#define EMUIF_S2 BIT_POINT((uint32_t)(&(EMU->IF)),20)
#define EMUIF_UZ BIT_POINT((uint32_t)(&(EMU->IF)),21)
#define EMUIF_I1Z BIT_POINT((uint32_t)(&(EMU->IF)),22)
#define EMUIF_I2Z BIT_POINT((uint32_t)(&(EMU->IF)),23)

//-----------------------RTC->CTL------------------------
#define RTCCTL_FOUT0 BIT_POINT((uint32_t)(&(RTC->CTL)),0)
#define RTCCTL_FOUT1 BIT_POINT((uint32_t)(&(RTC->CTL)),1)
#define RTCCTL_FOUT2 BIT_POINT((uint32_t)(&(RTC->CTL)),2)
#define RTCCTL_TCP0 BIT_POINT((uint32_t)(&(RTC->CTL)),3)
#define RTCCTL_TCP1 BIT_POINT((uint32_t)(&(RTC->CTL)),4)
#define RTCCTL_TCP2 BIT_POINT((uint32_t)(&(RTC->CTL)),5)
#define RTCCTL_TSE0 BIT_POINT((uint32_t)(&(RTC->CTL)),6)
#define RTCCTL_TSE1 BIT_POINT((uint32_t)(&(RTC->CTL)),7)
#define RTCCTL_WRTC BIT_POINT((uint32_t)(&(RTC->CTL)),8)
#define RTCCTL_WRBUSY BIT_POINT((uint32_t)(&(RTC->CTL)),9)
#define RTCCTL_CALBUSY BIT_POINT((uint32_t)(&(RTC->CTL)),10)
#define RTCCTL_LOSCCPS BIT_POINT((uint32_t)(&(RTC->CTL)),11)

//-----------------------RTC->IE------------------------
#define RTCIE_ALM BIT_POINT((uint32_t)(&(RTC->IE)),0)
#define RTCIE_CNT1 BIT_POINT((uint32_t)(&(RTC->IE)),1)
#define RTCIE_CNT2 BIT_POINT((uint32_t)(&(RTC->IE)),2)
#define RTCIE_SC BIT_POINT((uint32_t)(&(RTC->IE)),3)
#define RTCIE_MN BIT_POINT((uint32_t)(&(RTC->IE)),4)
#define RTCIE_HR BIT_POINT((uint32_t)(&(RTC->IE)),5)
#define RTCIE_DT BIT_POINT((uint32_t)(&(RTC->IE)),6)
#define RTCIE_MO BIT_POINT((uint32_t)(&(RTC->IE)),7)
#define RTCIE_IECLKEN BIT_POINT((uint32_t)(&(RTC->IE)),8)

//-----------------------RTC->IF------------------------
#define RTCIF_ALM BIT_POINT((uint32_t)(&(RTC->IF)),0)
#define RTCIF_CNT1 BIT_POINT((uint32_t)(&(RTC->IF)),1)
#define RTCIF_CNT2 BIT_POINT((uint32_t)(&(RTC->IF)),2)
#define RTCIF_SC BIT_POINT((uint32_t)(&(RTC->IF)),3)
#define RTCIF_MN BIT_POINT((uint32_t)(&(RTC->IF)),4)
#define RTCIF_HR BIT_POINT((uint32_t)(&(RTC->IF)),5)
#define RTCIF_DT BIT_POINT((uint32_t)(&(RTC->IF)),6)
#define RTCIF_MO BIT_POINT((uint32_t)(&(RTC->IF)),7)

//-----------------------LCD->CTL------------------------
#define LCDCTL_EN BIT_POINT((uint32_t)(&(LCD->CTL)),0)
#define LCDCTL_DUTY0 BIT_POINT((uint32_t)(&(LCD->CTL)),1)
#define LCDCTL_DUTY1 BIT_POINT((uint32_t)(&(LCD->CTL)),2)
#define LCDCTL_DUTY2 BIT_POINT((uint32_t)(&(LCD->CTL)),3)
#define LCDCTL_BIAS BIT_POINT((uint32_t)(&(LCD->CTL)),4)
#define LCDCTL_TYPE BIT_POINT((uint32_t)(&(LCD->CTL)),11)
#define LCDCTL_PWD_PUM BIT_POINT((uint32_t)(&(LCD->CTL)),12)

//-----------------------LCD->CTL---------------------
#define LCDSTATUS_DON BIT_POINT((uint32_t)(&(LCD->STAT)),0)
#define LCDSTATUS_DOFF BIT_POINT((uint32_t)(&(LCD->STAT)),1)
#define LCDSTATUS_IRQONEN BIT_POINT((uint32_t)(&(LCD->STAT)),2)
#define LCDSTATUS_IRQOFFEN BIT_POINT((uint32_t)(&(LCD->STAT)),3)
#define LCDSTATUS_COMLOW BIT_POINT((uint32_t)(&(LCD->STAT)),4)
#define LCDSTATUS_LCD_BUSY BIT_POINT((uint32_t)(&(LCD->STAT)),6)

//-----------------------TC0->CCFG---------------------
